spring.application.name=inpoll-backend
spring.datasource.url=jdbc:mariadb://${DB_HOST:localhost}:3306/inpoll?createDatabaseIfNotExist=true
spring.datasource.username=root
spring.datasource.password=<YOUR_PASSWORD_HERE>
spring.jpa.hibernate.ddl-auto=update
spring.jpa.open-in-view=false
